name: stroke_order_animator
description: Stroke order animations and quizzes for Chinese characters for use in Flutter apps

version: 1.6.0

homepage: https://github.com/Mr-Pepe/stroke-order-animator

repository: https://github.com/Mr-Pepe/stroke-order-animator

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  svg_path_parser: ^0.1.1
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true